package main

import (
	"github.com/gin-gonic/gin"
	_ "github.com/happyphper/gin-swagger-demo/docs" // docs is generated by Swag CLI, you have to import it.
)

var swagHandler gin.HandlerFunc

// @title API Demo
// @version 1.0
// @description This is a sample server Petstore server.

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := gin.New()

	if swagHandler != nil {
		r.GET("/swagger/*any", swagHandler)
	}

	_ = r.Run("127.0.0.1:8080")
}